name: 'Delta Action'
description: 'Compute delta offenses for your pull requests'
author: 'Factorial'
inputs:
  head_ref:
    required: true
    description: 'Name of your branch head. (Ex: github.head_ref)'
  forkpoint:
    required: true
    description: 'Commit id of your branch forkpoint.'
runs:
  using: 'node16'
  main: 'dist/index.js'
