name: 'Delta Action'
description: 'Compute delta offenses for your pull requests'
author: 'Factorial'
inputs:
  engine:
    required: true
    description: 'Engine used to compare deltas (rubocop, semgrep, eslint)'
  main:
    required: true
    description: 'File path with results of your engine for the main branch'
  branch:
    required: true
    description: 'File path with results of your engine for the branch. It can be a subset of result of changed files'
  head_ref:
    required: true
    description: 'Name of your branch head. (Ex: github.head_ref)'
  forkpoint:
    required: true
    description: 'Commit id of your branch forkpoint.'
  monorepo_prefix:
    required: false
    default: ''
    description: 'Monorepo prefix for the analysis files in main and branch fields.'
runs:
  using: 'node16'
  main: 'dist/index.js'
